# Generated by Django 5.1.3 on 2024-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('idprovedor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=15)),
                ('precio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=100)),
                ('idsucursal', models.CharField(max_length=50)),
            ],
        ),
    ]
