# Generated by Django 5.1.3 on 2024-11-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('idproducto', models.CharField(max_length=50)),
                ('idcliente', models.CharField(max_length=15)),
                ('idsucursal', models.CharField(max_length=50)),
                ('idempleado', models.CharField(max_length=25)),
                ('total', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
            ],
        ),
    ]
