# Generated by Django 5.1.3 on 2024-11-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provedores_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provedores',
            old_name='Precio',
            new_name='precio',
        ),
    ]
