# Generated by Django 5.1.3 on 2024-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=15)),
                ('numero', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=25)),
                ('salario', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
    ]
