# Generated by Django 5.1.3 on 2024-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('idempleados', models.CharField(max_length=25)),
                ('horario', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
    ]
