# Generated by Django 5.1.3 on 2024-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=15)),
                ('numero', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('codigop', models.CharField(max_length=50)),
            ],
        ),
    ]
